import "./globals.css";
import "ui/styles.css";
import type { Metadata } from "next";
import {  Sofia_Sans } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

const sofi = Sofia_Sans({subsets: ["latin"]})
export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
//   const myHeaders = new Headers();
// myHeaders.append("Authorization", "Basic YWRtaW46QWRtaW4xMjM=");
// myHeaders.append("Cookie", "JSESSIONID=F7FD5C5C2E82F850C47BBBE0EB6  76C14");

// const requestOptions = {
//   method: 'GET',
//   headers: myHeaders,
  
// };

// fetch("http://ec2-54-89-0-153.compute-1.amazonaws.com:8080/openmrs/ws/fhir2/R4/Patient/5071eb13-9c2b-416b-9eec-19f3c0d8ffd7", requestOptions)
//   .then(response => response.json())
//   .then(result => console.log(result))
//   .catch(error => console.log('error', error));
  return (
    <html lang="en">
      <body className={sofi.className}>{children}</body>
    </html>
  );
}
